### ISSUE TITLE
Allow use of Environment Variable in Configuration File

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/bundle-chroot-builder#11]
It would be very advantageous to allow the use of environment variables, such a `$HOME`, in the builder configuration file.  When used in an automated build environment like Jenkins or Travis, it would be helpful to use environment variables for the various paths.

NOTE: This will require a compatible change to the `mixer` tool as it also reads the same configuration file.

See https://github.com/clearlinux/mixer-tools/issues/28

**Comment by tmarcu** [comment]
Merged, will be in official release.
